name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
  screenshots:
    name: Capture screenshots
    runs-on: macos-latest
    needs: test
    steps:
      - name: Git
        run: git show
      - name: Capture screenshot
        run: screencapture screenshot.png
      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
