name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  screenshots:
    name: Capture screenshots
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn build:publish
      - run: git config core.pager "./build/git-split-diffs --color"
      - run: git show
      - run: screencapture screenshot.png
      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
